version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "react-app"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
